#!/usr/bin/env python3
"""
Main entry point for the Adaptive Learning System
Run with: uvicorn main:app --reload --port 4000
"""

import os
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pymongo import ASCENDING

from api.adaptive_routes import router as adaptive_router
from config.database import (
    adaptive_learning_collection,
    adaptivequiz_collection,
    adaptivequiz_submissions_collection,
    db_manager,
    item_parameters_collection,
    learner_ability_collection,
)
from services.sakt_service import sakt_service

# The Node backend defaults to http://localhost:4000 for this service
# (ADAPTIVE_LEARNING_URL); keep the default port in sync with it.
PORT = int(os.getenv("ADAPTIVE_PORT", "4000"))

# Browsers reject `Access-Control-Allow-Origin: *` together with credentials, so
# list the front ends explicitly instead of silently breaking cookie auth.
CORS_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ORIGINS", "http://localhost:5173,http://localhost:3000,http://localhost:8000"
    ).split(",")
    if origin.strip()
]


def ensure_indexes() -> None:
    """Indexes for the queries this service runs on every request."""
    adaptive_learning_collection.create_index(
        [("student", ASCENDING), ("course", ASCENDING)], unique=True
    )
    adaptivequiz_collection.create_index(
        [("student_id", ASCENDING), ("unit_id", ASCENDING),
         ("learning_objective_index", ASCENDING), ("created_at", -1)]
    )
    adaptivequiz_collection.create_index([("student_id", ASCENDING), ("created_at", -1)])
    adaptivequiz_submissions_collection.create_index(
        [("student_id", ASCENDING), ("submitted_at", -1)]
    )
    # Read on every answer by the online learner, so they must be indexed.
    learner_ability_collection.create_index(
        [("student", ASCENDING), ("course", ASCENDING),
         ("unit", ASCENDING), ("learningObjectiveIndex", ASCENDING)],
        unique=True,
    )
    item_parameters_collection.create_index(
        [("course", ASCENDING), ("unit", ASCENDING),
         ("learningObjectiveIndex", ASCENDING), ("difficulty", ASCENDING)],
        unique=True,
    )


@asynccontextmanager
async def lifespan(app: FastAPI):
    print("\n" + "=" * 70)
    print("ADAPTIVE LEARNING SYSTEM STARTING")
    print("=" * 70)
    app.state.db_ready = False
    try:
        db_manager.get_database().command("ping")
        app.state.db_ready = True
        print("MongoDB connected")
        ensure_indexes()
        print("Indexes ensured")
    except Exception as e:
        print(f"MongoDB connection failed: {e}")

    # Load the knowledge-tracing model once. A failure here is not fatal: the
    # engine falls back to its rule-based path and says so.
    if sakt_service.initialize():
        print(
            f"SAKT knowledge tracing ready "
            f"({sakt_service.num_skills} skills, epoch {sakt_service.metadata.get('epoch')})"
        )
        if sakt_service.num_skills:
            print("  note: skill space is unit-level; objective progression stays rule-based")
    else:
        print(f"SAKT unavailable ({sakt_service.status}) - using rule-based adaptation only")

    print(f"API docs: http://localhost:{PORT}/docs")
    print("=" * 70 + "\n")
    yield


app = FastAPI(
    title="Adaptive Learning System",
    description=(
        "Adaptive assessment engine. SAKT knowledge tracing drives difficulty and "
        "pace; evidence-based rules drive per-objective progression; questions are "
        "generated by Gemini from the unit's own material."
    ),
    version="1.2.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(adaptive_router, prefix="/api/adaptive", tags=["Adaptive Learning"])


@app.get("/")
def root():
    return {
        "status": "running",
        "service": "Adaptive Learning System",
        "version": "1.1.0",
        "documentation": "/docs",
    }


@app.get("/health")
def health_check():
    """Report the real state of the dependencies rather than a fixed 'healthy'."""
    try:
        db_manager.get_database().command("ping")
        database = "connected"
    except Exception as e:
        database = f"error: {e}"

    healthy = database == "connected"
    return {
        "status": "healthy" if healthy else "degraded",
        "database": database,
        "generator": "gemini-2.5-flash",
        # Reported rather than assumed: the service runs either way, and callers
        # should be able to tell which adaptation path is live.
        "knowledge_tracing": sakt_service.health(),
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="0.0.0.0", port=PORT, reload=True)
